### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by kaspergrubbe** [mikegioia/pki#1]
It looks like an interesting and helpful piece of software, it would be nice with some examples and scope of the project in the README.

**Comment by mikegioia** [comment]
That's a great idea. For now you could try `-h` in the scripts but you're right, it needs a README.

**Comment by mikegioia** [comment]
I removed all of the non-essential stuff from this repo and got it down to the scripts and config files. I just got started on the README too, and everything will be done in this branch for now https://github.com/mikegioia/pki/tree/readme-updates.

It should be up pretty soon :D

**Comment by mikegioia** [comment]
@kaspergrubbe It took like 2 years but I got it done! The README is now complete and I went through and updated all of the scripts again. It works on Linux and Mac now.

**Comment by kaspergrubbe** [comment]
@mikegioia Thank! 👍
